# Generated by Django 6.0.2 on 2026-02-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='student/'),
        ),
    ]
