# Generated by Django 6.0.2 on 2026-02-26 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.CharField(default=datetime.date.today),
        ),
    ]
